  services:
    postgres:
      image: postgres:latest
      restart: always
      env_file:
        - .env
      environment:
        POSTGRES_DB: jobfair
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data

    hasura:
      image: hasura/graphql-engine:latest
      restart: always
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      env_file:
        - .env
      environment:
        HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/jobfair"
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
        HASURA_GRAPHQL_DEV_MODE: "true"
        HASURA_GRAPHQL_ADMIN_SECRET: ironwoman890

    nestjs:
      build: .
      depends_on:
        - postgres
        - hasura
      ports:
        - "3000:3000"
      env_file:
        - .env
      environment:
        HASURA_GRAPHQL_ADMIN_SECRET: ironwoman890
        HASURA_GRAPHQL_ENDPOINT: http://hasura:8080/v1/graphql
        DATABASE_URL: "postgres://postgres:postgres@postgres:5432/jobfair"
      volumes:
        - .:/app
        - /app/node_modules
      working_dir: /app
      command: ["npm", "run", "start:dev"]
      develop:
        watch:
          - action: sync
            path: . # Sync all files
            target: /app
            ignore:
              - node_modules/
          - action: rebuild
            path: package.json

  volumes:
    pg_data: